apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.name}}
    version: {{.Values.version}}
  name: {{.Values.name}}
  namespace: default
spec:
  replicas: {{.Values.numberOfReplicas}}
  minReadySeconds: {{.Values.minReadySeconds}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.name}}
        version: {{.Values.version}}
    spec:
      containers:
        - image: {{.Values.imageName}}
          imagePullPolicy: IfNotPresent
          name: {{.Values.name}}
          ports:
            - name: liveness-port
              containerPort: {{.Values.port}}

          resources:
            requests:
              memory: {{.Values.resourceRequestMemory}}
            limits:
              memory: {{.Values.resourceLimitsMemory}}
          readinessProbe:
            httpGet:
              path: {{.Values.healthCheck}}
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: {{.Values.healthCheck}}
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: {{.Values.Always}}
      terminationGracePeriodSeconds: {{.Values.terminationGracePeriodSeconds}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.name}}
    version: {{.Values.version}}
  name: {{.Values.name}}
spec:
  ports:
    - name: http
      port: {{.Values.port}}
  selector:
    app: {{.Values.name}}
    version: {{.Values.version}}
  type: {{.Values.serviceType}}
