apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-hello-world
    version: 0.0.2-SNAPSHOT
  name: spring-boot-hello-world
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: spring-boot-hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-boot-hello-world
        version: 0.0.2-SNAPSHOT
    spec:
      containers:
        - image: amsidhmicroservice/spring-boot-hello-world:latest
          imagePullPolicy: IfNotPresent
          name: spring-boot-hello-world
          ports:
            - name: liveness-port
              containerPort: 8181

          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-hello-world
    version: 0.0.2-SNAPSHOT
  name: spring-boot-hello-world
spec:
  ports:
    - name: http
      port: 8181
  selector:
    app: spring-boot-hello-world
    version: 0.0.2-SNAPSHOT
  type: LoadBalancer
