image:
  repository: amsidhmicroservice/spring-boot-hello-world
  tag: 0.0.2-SNAPSHOT

port: 8181
name: spring-boot-hello-world
healthCheck: /
serviceType: LoadBalancer  # To be uncommented for spring-boot-hello-world

version: 0.0.2-SNAPSHOT
minReadySeconds: 45
resourceRequestMemory: 512Mi
resourceLimitsMemory: 1024Mi
restartPolicy: Always
terminationGracePeriodSeconds: 30
numberOfReplicas: 2

